routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});


//frontend route
Route::get('/eshop','ShopController@index')->name('resources.home');
Route::get('/resources/shop_left_sidebar2','ShopController@sidebar2')->name('resources.sidebar2');
Route::get('/resources/shop_product/{product}','ShopController@sp')->name('resources.shop_product');
Route::get('/resources/shop_billing','ShopController@bl')->name('resources.shop_billing');
Route::get('/resources/login','ShopController@login')->name('resources.login');
Route::post('/resources/customer/login','ShopController@login_customer')->name('customer.login');
Route::get('/resources/customer/logout','ShopController@logout_customer')->name('customer.logout');
Route::get('/resources/register','ShopController@register')->name('resources.register');
Route::post('/resources/customer','ShopController@register_customer')->name('customer.register');
Route::get('/resources/contact','ShopController@contact')->name('resources.contact');
Route::post('/resources/search','ShopController@search')->name('resources.search');
Route::post('/resources/sorting','ShopController@sorting')->name('resources.sorting');

Route::post('/resources/shop_add_cart','CartController@addcart')->name('resources.addcart');
Route::get('/resources/shop_cart','CartController@index')->name('resources.cart');
Route::get('/resources/remove_cart/{id}','CartController@remove')->name('resources.cart_remove');
Route::post('/resources/shipping_info','ShippingController@store')->name('shipping.store');
Route::get('/resources/payment','CheckoutController@payment_info')->name('payment.form');
Route::post('/resources/new_order','CheckoutController@saveOrderInfo')->name('payment.store');
Route::get('/checkout/complete-order','CheckoutController@complete')->name('order.complete');
Route::get('/resources/shop_product/category/{id}','ShopController@category_products')->name('category.products');
Route::get('/resources/shop_product/brand/{id}','ShopController@brand_products')->name('brand.products');
Route::get('/resources/shop_product/supplier/{id}','ShopController@supplier_products')->name('supplier.products');
Route::get('/resources/shop_product/sub_category/{id}','ShopController@sub_category_products')->name('sub_category.products');




//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

//backend
Route::group(['middleware' => ['auth']], function () {
    Route::get('/admin', 'HomeController@index');
    Route::get('/users/{user}/profile', 'HomeController@showProfile')->name('admin.profile');
    Route::get('/', 'HomeController@index');

    Route::get('/categories/trash','CategoryController@trash')->name('categories.trash');
    Route::get('/categories/trash/{id}/restore','CategoryController@restore')->name('categories.restore');
    Route::delete('/categories/trash/{id}/delete','CategoryController@delete')->name('categories.delete');
    Route::resource('/categories','CategoryController');

    Route::get('/products/trash', 'ProductController@trash')->name('products.trash');
    Route::get('/products/status/{id}/change', 'ProductController@changeStatus')->name('products.status');
    Route::get('/products/trash/{id}/restore','ProductController@restore')->name('products.restore');
    Route::delete('/products/trash/{id}/delete','ProductController@delete')->name('products.delete');
    Route::resource('/products','ProductController');

    Route::resource('/brands', 'BrandController');


    Route::get('/sub_categories/trash','Sub_categoryController@trash')->name('sub_categories.trash');
    Route::get('/sub_categories/trash/{id}/restore','Sub_categoryController@restore')->name('sub_categories.restore');
    Route::delete('/sub_categories/trash/{id}/delete','Sub_categoryController@delete')->name('sub_categories.delete');
    Route::resource('/sub_categories', 'Sub_categoryController');

    Route::resource('/suppliers', 'SupplierController');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/products/order/manage','OrderController@manageOrder')->name('manage.order');
    Route::get('/products/order/view/{id}','OrderController@viewOrderDetail')->name('view-order-detail');
    Route::get('/products/change/order/status/{id}','OrderController@changeOrderStatus')->name('change-status-order-detail');
    Route::get('/products/delete/order/{id}','OrderController@deleteOrder')->name('delete-order-detail');
    Route::get('/products/order/{id}/invoice','OrderController@OrderInvoice')->name('order.invoice');
});


//authetication route

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');



//Route::get('/users/{user}/profile', 'ShowProfile')->name('users.profile');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;
    protected $fillable = [
    		'brand_id',
        'category_id','sub_category_id',
    		'title',
    		'picture1',
    		'picture2',
    		'price',
    		'quantity','popularity_count'

    ];
    
    protected $dates=['deleted_at'];
    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function sub_category()
    {
        return $this->belongsTo(Sub_category::class);
    }
    public function suppliers()
    {
        return $this->belongsToMany(Supplier::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Brand;
use App\Category;
use App\Sub_category;
use Illuminate\Http\Request;
use App\Http\Requests\ProductRequest;
use Carbon\Carbon;
use App\Product;
use App\Supplier;
use Illuminate\Support\Facades\DB;
use Image;

class ProductController extends Controller
{

    const UPLOAD_DIR = '/uploads/products/';

    public function index()
    {
        $paginatePerPage = 4;
        $pageNumber = request('page');
        if(!is_null($pageNumber)){
            $serial = $paginatePerPage * $pageNumber - $paginatePerPage;
        }else{
            $serial = 0;
        }

        $products = Product::latest()->paginate($paginatePerPage);

        return view('backend.products.index',compact('products','serial'));
    }

    public function create()
    {
        $brands = Brand::pluck('title', 'id');
        $categories = Category::pluck('title', 'id');
        $sub_categories =Sub_category::pluck('title', 'id');
        $suppliers = Supplier::get(['title', 'id']);
        $selectedSuppliers = [];
        return view('backend.products.create',compact('brands', 'suppliers', 'selectedSuppliers','categories','sub_categories'));
    }

    public function changeStatus($id)
    {
        $data=Product::findOrFail($id);
        $status=$data->status;
        if($status==0){
            DB::table('products')->where('id',$id)->update(['status' => 1]);
            return redirect()->back();
        }else{
            DB::table('products')->where('id',$id)->update(['status' => 0]);
            return redirect()->back();
        }
    }

    public function store(Request $request)
    {
        $data =  $request->all();
        if($request->hasFile('image1')){
            $data['picture1'] = $this->uploadImage($request->image1);
        }
        if($request->hasFile('image2')){
            $data['picture2'] = $this->uploadImage($request->image2);
        }

//        dd($data);
        $product=Product::create($data);
        $product->suppliers()->attach($request->supplier_ids);

        return redirect()->route('products.index');
    }

    public function show(Product $product)
    {
        return view('backend.products.show' ,compact('product'));
    }

    public function edit(Product $product)
    {
        $brands = Brand::pluck('title', 'id');
        $categories = Category::pluck('title', 'id');
        $sub_categories =Sub_category::pluck('title', 'id');
        $suppliers = Supplier::get(['title', 'id']);
        $selectedSuppliers = [];

        return view('backend.products.edit',compact('product','brands', 'suppliers', 'selectedSuppliers','categories','sub_categories'));
    }

    public function update(Request $request, Product $product)
    {
        if($request->hasFile('image1')){
            $product['picture1'] = $this->uploadImage($request->image1);
        }
        if($request->hasFile('image2')){
            $product['picture2'] = $this->uploadImage($request->image2);
        }
        $product->update($request->all());
        return redirect()->route('products.index');
     }


    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->route('products.index');
    }
    public function trash()
    {
        $products = Product::onlyTrashed()->get();
        return view('backend.products.trash', compact('products'));
    }
    public function restore($id)
    {
        $product = Product::onlyTrashed()
            ->where('id', $id)
            ->first();

        $product->restore();
        return redirect()->back();
    }
    public function delete($id)
    {
    $product = Product::onlyTrashed()
                ->where('id', $id)
                ->first();
    $this->unlink($product->picture1);
    $this->unlink($product->picture2);
    $product->suppliers()->detach();
    $product->forceDelete();
    return redirect()->back();
    }
     private function uploadImage($file)
    {
        $random= rand(1,100);
        $timestamp = str_replace([' ', ':'], '-', Carbon::now()->toDateTimeString());//formatting the name for unique and readable
        $file_name =  $timestamp.'_'.$random.'.'.$file->getClientOriginalExtension();
        Image::make($file)->resize(300, 300)->save(public_path() . self::UPLOAD_DIR . $file_name);
        return $file_name;
    }

    private function unlink($file)
    {
        if ($file != '' && file_exists(public_path() . self::UPLOAD_DIR . $file)) {
            @unlink(public_path() . self::UPLOAD_DIR . $file);
        }
    }

    
    
    
    


}

resources/views/backend/products/create.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="card">
    <div class="card-header">
        <div class="float-left">
            Create Post
        </div>
        <div class="float-right">
            <a href="{{ route('products.index') }}" class="btn btn-primary">List</a>
        </div>
    </div>
    <div class="card-body">

        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif

        {{--    <form action="{{ route('products.store') }}" method="post">--}}
        {!! Form::open(['route' => 'products.store', 'files' => true]) !!}
        {{--@csrf--}}

            {{--<input type="text" name="title" required placeholder="Enter Category Title Here"><br>--}}
        @include('backend.products.form')
        <div class="form-group row">
            <div class="col-sm-10 text-center">
                {!! Form::button('Add', [
                                            'class' => 'btn btn-primary',
                                            'type' => 'submit',
                                        ]) !!}
            </div>
        </div>
        {!! Form::close() !!}
        {{--</form>--}}
    </div>
</div>
@endsection

resources/views/backend/products/edit.blade.php
@extends('backend.layouts.master')

@section('content')
    <div class="card">
        <div class="card-header">
            <div class="float-left">
                Edit Product
            </div>
            <div class="float-right">
                <a href="{{ route('products.index') }}" class="btn btn-primary">List</a>
            </div>
        </div>
        <div class="card-body">

            @if ($errors->any())
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif
              {!! Form::model($product,[
                        'route' => ['products.update',$product->id],
                        'method' => 'put',
                        'files' => true,
                        ])!!}
            <fieldset>
                <legend>Edit Product</legend>
                    @include('backend.products.form')
                <div class="form-group row">
                    <div class="col-sm-10 text-center">
                        {!! Form::button('Update',[
                            'class' => 'btn btn-primary',
                            'type' => 'submit',
                        ])!!}
                        
                    </div>
                </div>
            </fieldset>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/backend/products/form.blade.php
<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('Title', null, ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        {!! Form::text('title', null, [
                'class' => 'form-control',
                'id' => 'Title',
            ]) !!}<br>
        @if ($errors->has('title'))
            {{ $errors->first('title') }}
        @endif
    </div>
</div>

<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('Brand', null, ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        {!! Form::select('brand_id',$brands, null, [
                'placeholder' => 'Select Brand',
                'class' => 'form-control',
                'id' => 'brand_id',
            ]) !!}<br>
    </div>
</div>
<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('Category', null, ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        {!! Form::select('category_id',$categories, null, [
                'placeholder' => 'Select Category',
                'class' => 'form-control',
                'id' => 'category_id',
            ]) !!}<br>
    </div>
</div>

<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('Sub Category', null, ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        {!! Form::select('sub_category_id',$sub_categories, null, [
                'placeholder' => 'Select Sub Category',
                'class' => 'form-control',
                'id' => 'sub_category_id',
            ]) !!}<br>
    </div>
</div>



<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('image1', null, ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        {!! Form::file('image1', [
                'class' => 'form-control',
                'id' => 'image1',
            ]) !!}<br>
        @if ($errors->has('image1'))
            {{ $errors->first('image1') }}
        @endif
    </div>
</div>

<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('image2', null, ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        {!! Form::file('image2', [
                'class' => 'form-control',
                'id' => 'image2',
            ]) !!}<br>
        @if ($errors->has('image2'))
            {{ $errors->first('image2') }}
        @endif
    </div>
</div>
<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('Price', null, ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        {!! Form::text('price', null, [
                'class' => 'form-control',
                'id' => 'price',
            ]) !!}<br>
        @if ($errors->has('price'))
            {{ $errors->first('price') }}
        @endif
    </div>
</div>
<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('Quantity', null, ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        {!! Form::text('quantity', null, [
                'class' => 'form-control',
                'id' => 'quantity',
            ]) !!}<br>
        @if ($errors->has('quantity'))
            {{ $errors->first('Quantity') }}
        @endif
    </div>
</div>
<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}
    {!! Form::label('Suppliers', null , ['class' => 'col-sm-2 col-form-label']) !!}

    <div class="col-sm-10">
        @foreach ($suppliers as $supplier)
            <div class="checkbox">
                <label>
                    {{ Form::checkbox('supplier_ids[]', $supplier->id, in_array($supplier->title, $selectedSuppliers), ['class' => 'field']) }}
                    {{ $supplier->title }}
                </label>
            </div>
        @endforeach
    </div>
</div>

resources/views/backend/products/index.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="card">
    <div class="card-header">
        <div class="float-left">
            Products
        </div>
        <div class="float-right">
                <a href="{{ route('products.trash') }}" class="btn btn-primary">Trash</a>
                <a href="{{ route('products.create') }}" class="btn btn-primary">Add New</a> 
        </div>
    </div>
    <div class="card-body">

        @include('backend.layouts.elements.error')

        <table id="order-listing" class="table">
            <thead>
                <tr>
                <th>SL#</th>
                <th>Title</th>
                <th>Brand Name</th>
                <th>Category</th>
                <th>Sub_Category</th>
                <th>Image 1</th>
                <th>Image 2</th>
                <th>Price</th>
                <th>Quanatity</th>
                <th>Action</th>
                </tr>
            </thead>
            <tbody>
               @foreach($products as $product)
                <tr>
                    <td>{{ ++$serial }}</td>
                    <td>{{ $product->title}}</td>
                    <td>{{ $product->brand->title }}</td>
                    <td>{{ $product->category->title }}</td>
                    <td>{{ $product->sub_category->title }}</td>
                    <td>
                    <img src="{{asset('uploads/products/'.$product->picture1)}}" width='60' alt="" />
                    </td>
                    <td>
                        <img src="{{asset('uploads/products/'.$product->picture2)}}" width='60' alt="" />
                    </td>
                    <td>{{$product->price}}</td>
                    <td>{{$product->quantity}}</td>
                    <td>
                        <a href='{{route("products.show",$product->id)}}' class='btn btn-sm btn-info'>Show</a>
                        <a href='{{route("products.edit",$product->id)}}' class='btn btn-sm btn-warning'>Edit</a>
                        {!! Form::open([
                        'route'=>['products.destroy',$product->id],
                        'files'=>true,'method'=>'delete',
                        'style'=>'display:inline',
                        ])!!}
                            {{ Form::button('Delete',[
                            'class'=>'btn btn-sm btn-danger','type'=>'submit',
                            ]) }}
                        {!! Form::close() !!}
                        <?php if($product->status==0){?>

                        <a href='{{route("products.status",$product->id)}}' class='btn btn-sm btn-warning'>Deactive</a>
                        <?php }else{?>
                        <a href='{{route("products.status",$product->id)}}' class='btn btn-sm btn-warning'>Active </a>
                    <?php }?>
                    </td>
                </tr>
                @endforeach

            </tbody>
        </table>
        <div class="float-right">

        </div>
    </div>
</div>
@endsection

resources/views/backend/products/show.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="card">
    <div class="card-header">

        <div class="float-left">
            Products Details
        </div>

        <div class="float-right">
            <a href="{{ route('products.index') }}" class="btn btn-primary">List</a>
        </div>

    </div>
    <div class="card-body">

        <table class="table table-bordered table-striped">

            <tr>
                <td>Title</td>
                <td>{{ $product->title }}</td>
            </tr>

            <tr>
                <td>Brand Name</td>
                <td>{{ $product->brand->title }}</td>
            </tr>

            <tr>
                <td>Image 1</td>
                <td><img src="{{ asset('/uploads/products/'. $product->picture1) }}" alt=""></td>
            </tr>
            <tr>
                <td>Image 2</td>
                <td><img src="{{ asset('/uploads/products/'. $product->picture2) }}" alt=""></td>
            </tr>
            <tr>
                <td>Price</td>
                <td>{!! $product->price !!}</td>
            </tr>
            <tr>
                <td>Quantity</td>
                <td>{!! $product->quantity !!}</td>
            </tr>
            <tr>
                <td>Suppliers</td>
                <td>
                    @foreach($product->suppliers as $supplier)
                        <a href="#">{{ $supplier->title }}</a> |
                    @endforeach
                </td>
            </tr>
        </table>
    </div>
</div>
@endsection

resources/views/backend/products/trash.blade.php
@extends('backend.layouts.master')

@section('content')
    <div class="card">
        <div class="card-header">
            <div class="float-left">
                Deleted Products
            </div>
            <div class="float-right">
                <a href="{{ route('products.index') }}" class="btn btn-primary">List</a>
            </div>
        </div>
        <div class="card-body">

            <table class="table table-bordered table-striped">
                <tr>
                    <th width="100">SL#</th>
                    <th>Title</th>
                    <th>Brand Name</th>
                    <th>Image 1</th>
                    <th>Image 2</th>
                    <th>Price</th>
                    <th>Quanatity</th>
                    <th width="220" class="text-right">Action</th>
                </tr>
                @php $serial = 0; @endphp
                @foreach($products as $product)
                    <tr>
                        <td>{{ ++$serial }}</td>
                        <td>{{ $product->title }}</td>
                        <td>{{$product->brand_id}}</td>
                        <td>
                            <img src="{{asset('uploads/products/'.$product->picture1)}}" width='60' alt="" />
                        </td>
                        <td>
                            <img src="{{asset('uploads/products/'.$product->picture2)}}" width='60' alt="" />
                        </td>
                        <td>{{$product->price}}</td>
                        <td>{{$product->quantity}}</td>
                        <td class="text-right">
                            <a href='{{route("products.show",$product->id)}}' class='btn btn-sm btn-info'>Show</a>
                            <a href="{{ route('products.restore', $product->id) }}" class="btn btn-sm btn-warning">Restore</a>
                            {!! Form::open([
                                            'route' => ['products.delete', $product->id],
                                            'method' => 'delete',
                                            'files' =>true,
                                            'style' => 'display:inline',
                                        ]) !!}
                            {!! Form::button('Delete',[
                                    'type' => 'submit',
                                    'class' => "btn btn-sm btn-danger",
                                    'onclick' => 'return confirm("Are You Sure Want To Delete Permanently ?")',

                            ]) !!}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
@endsection