routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});


//frontend route
Route::get('/eshop','ShopController@index')->name('resources.home');
Route::get('/resources/shop_left_sidebar2','ShopController@sidebar2')->name('resources.sidebar2');
Route::get('/resources/shop_product/{product}','ShopController@sp')->name('resources.shop_product');
Route::get('/resources/shop_billing','ShopController@bl')->name('resources.shop_billing');
Route::get('/resources/login','ShopController@login')->name('resources.login');
Route::post('/resources/customer/login','ShopController@login_customer')->name('customer.login');
Route::get('/resources/customer/logout','ShopController@logout_customer')->name('customer.logout');
Route::get('/resources/register','ShopController@register')->name('resources.register');
Route::post('/resources/customer','ShopController@register_customer')->name('customer.register');
Route::get('/resources/contact','ShopController@contact')->name('resources.contact');
Route::post('/resources/search','ShopController@search')->name('resources.search');
Route::post('/resources/sorting','ShopController@sorting')->name('resources.sorting');

Route::post('/resources/shop_add_cart','CartController@addcart')->name('resources.addcart');
Route::get('/resources/shop_cart','CartController@index')->name('resources.cart');
Route::get('/resources/remove_cart/{id}','CartController@remove')->name('resources.cart_remove');
Route::post('/resources/shipping_info','ShippingController@store')->name('shipping.store');
Route::get('/resources/payment','CheckoutController@payment_info')->name('payment.form');
Route::post('/resources/new_order','CheckoutController@saveOrderInfo')->name('payment.store');
Route::get('/checkout/complete-order','CheckoutController@complete')->name('order.complete');
Route::get('/resources/shop_product/category/{id}','ShopController@category_products')->name('category.products');
Route::get('/resources/shop_product/brand/{id}','ShopController@brand_products')->name('brand.products');
Route::get('/resources/shop_product/supplier/{id}','ShopController@supplier_products')->name('supplier.products');
Route::get('/resources/shop_product/sub_category/{id}','ShopController@sub_category_products')->name('sub_category.products');




//Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

//backend
Route::group(['middleware' => ['auth']], function () {
    Route::get('/admin', 'HomeController@index');
    Route::get('/users/{user}/profile', 'HomeController@showProfile')->name('admin.profile');
    Route::get('/', 'HomeController@index');

    Route::get('/categories/trash','CategoryController@trash')->name('categories.trash');
    Route::get('/categories/trash/{id}/restore','CategoryController@restore')->name('categories.restore');
    Route::delete('/categories/trash/{id}/delete','CategoryController@delete')->name('categories.delete');
    Route::resource('/categories','CategoryController');

    Route::get('/products/trash', 'ProductController@trash')->name('products.trash');
    Route::get('/products/status/{id}/change', 'ProductController@changeStatus')->name('products.status');
    Route::get('/products/trash/{id}/restore','ProductController@restore')->name('products.restore');
    Route::delete('/products/trash/{id}/delete','ProductController@delete')->name('products.delete');
    Route::resource('/products','ProductController');

    Route::resource('/brands', 'BrandController');


    Route::get('/sub_categories/trash','Sub_categoryController@trash')->name('sub_categories.trash');
    Route::get('/sub_categories/trash/{id}/restore','Sub_categoryController@restore')->name('sub_categories.restore');
    Route::delete('/sub_categories/trash/{id}/delete','Sub_categoryController@delete')->name('sub_categories.delete');
    Route::resource('/sub_categories', 'Sub_categoryController');

    Route::resource('/suppliers', 'SupplierController');

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/products/order/manage','OrderController@manageOrder')->name('manage.order');
    Route::get('/products/order/view/{id}','OrderController@viewOrderDetail')->name('view-order-detail');
    Route::get('/products/change/order/status/{id}','OrderController@changeOrderStatus')->name('change-status-order-detail');
    Route::get('/products/delete/order/{id}','OrderController@deleteOrder')->name('delete-order-detail');
    Route::get('/products/order/{id}/invoice','OrderController@OrderInvoice')->name('order.invoice');
});


//authetication route

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');



//Route::get('/users/{user}/profile', 'ShowProfile')->name('users.profile');

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    //
    protected $fillable=[
        'title','address'
    ];
    public function products()
    {
        return $this->belongsToMany(Product::class);
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Supplier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class SupplierController extends Controller
{
    function index(){
        $paginatePerPage=5;
        $pageNumber=request('page') ;

        if (!is_null($pageNumber)){
            $serial=$paginatePerPage*$pageNumber-$paginatePerPage;
        }else{
            $serial=0;
        }
        $suppliers = Supplier::paginate($paginatePerPage);
        return view('backend.suppliers.index',compact('suppliers','serial'));
    }
    function create(){
        return view('backend.suppliers.create');
    }
    function store(Request $request){
        $data=$request->all();

        if($request->hasFile('image')){
            $data['image'] = $this->uploadImage($request->image);
        }
        Supplier::create($data);
        Session::flash('message','Brand created successfully');
        return redirect('/suppliers');
    }
    function show(Supplier $supplier){

        return view('backend.suppliers.show',compact('supplier'));
    }
    function edit(Supplier $supplier){

        return view('backend.suppliers.edit',compact('supplier'));
    }
    function update(Request $request,Supplier $supplier){
        $supplier->update($request->all());
        Session::flash('message','Upadated succesfull');
        return redirect('/suppliers');
    }

    function destroy(Supplier $supplier){

        $supplier->delete();
        Session::flash('message','Deleted succesfull');

        return redirect('/suppliers');
    }
}

resources/views/backend/suppliers/create.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="card">
    <div class="card-header">
        <div class="float-left">
            Create Brand
        </div>
        <div class="float-right">
            <a href="{{ route('brands.index') }}" class="btn btn-primary">List</a>
        </div>
    </div>
    <div class="card-body">

        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        @endif

        {{--    <form action="{{ route('brands.store') }}" method="post">--}}
        {!! Form::open(['route' => 'suppliers.store']) !!}
        {{--@csrf--}}
        <fieldset>
            <legend>Add New Supplier</legend>
            {{--<input type="text" name="title" required placeholder="Enter Category Title Here"><br>--}}
            @include('backend.suppliers.form')
            <div class="form-group row">
                <div class="col-sm-10 text-center">
                    {!! Form::button('Add', [
                                                'class' => 'btn btn-primary',
                                                'type' => 'submit',
                                            ]) !!}
                </div>
            </div>
        </fieldset>
        {!! Form::close() !!}
        {{--</form>--}}
    </div>
</div>
@endsection

resources/views/backend/suppliers/edit.blade.php
@extends('backend.layouts.master')

@section('content')
    <div class="card">
        <div class="card-header">
            <div class="float-left">
                Edit Supplier
            </div>
            <div class="float-right">
                <a href="{{ route('suppliers.index') }}" class="btn btn-primary">List</a>
            </div>
        </div>
        <div class="card-body">

            @if ($errors->any())
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif
            {!! Form::model($supplier,[
                        'route' => ['suppliers.update', $supplier->id],
                        'method' => 'put'
                        ]) !!}
            <fieldset>
                <legend>Edit Supplier</legend>
                    @include('backend.suppliers.form')
                <div class="form-group row">
                    <div class="col-sm-10 text-center">
                        {!! Form::button('Update', [
                                                    'class' => 'btn btn-primary',
                                                    'type' => 'submit',
                                                ]) !!}
                    </div>
                </div>
            </fieldset>
            {!! Form::close() !!}
                {{--</form>--}}
        </div>
    </div>
@endsection

resources/views/backend/suppliers/form.blade.php
<div class="form-group row">
    {{--<label for="title" class="col-sm-2 col-form-label">Title</label>--}}


    <div class="col-sm-10">
        {!! Form::label('Title', null, ['class' => 'col-sm-2 col-form-label']) !!}
        {!! Form::text('title', null, [
                'placeholder' => 'Enter Title Title Here',
                'class' => 'form-control',
                'id' => 'Title',
            ]) !!}<br>
        {!! Form::label('Address', null, ['class' => 'col-sm-2 col-form-label']) !!}
        {!! Form::text('address', null, [
                        'placeholder' => 'Enter Address Here',
                        'class' => 'form-control',
                    ]) !!}
        <br>
        @if ($errors->has('title'))
            {{ $errors->first('title') }}
        @endif
    </div>
</div>

resources/views/backend/suppliers/index.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="card">
    <div class="card-header">
        <div class="float-left">
            Suppliers
        </div>
        <div class="float-right">
{{--            <a href="{{ route('suppliers.trash') }}" class="btn btn-primary">Trash</a>--}}
                 <a href="{{ route('suppliers.create') }}" class="btn btn-primary">Add New</a>
        </div>
    </div>
    <div class="card-body">

        @include('backend.layouts.elements.error')

        <table id="order-listing" class="table">
            <thead>
            <tr>
                <th>SL#</th>
                <th>Title</th>
                <th>Address</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody >
            @foreach($suppliers as $supplier)
                <tr data-expanded="true">
                    <td>{{ ++$serial }}</td>
                    <td>{{ $supplier->title }}</td>
                    <td>{{ $supplier->address }}</td>
                    <td>
                        <a class="btn btn-primary" href="{{ route('suppliers.show',$supplier->id) }}">show</a>
                        <a class="btn btn-warning" href="{{ route('suppliers.edit',$supplier->id) }}">edit</a>
                        {!! Form::open([
                          'route'=>['suppliers.destroy',$supplier->id],
                          'method'=>'delete',
                          'style'=>'display:inline'
                        ]) !!}
                        {!! Form::button('delete',[
                          'type'=>'submit',
                          'class'=>'btn btn-danger',
                          'onclick'=>'return confirm("Are you sure to delete?")'
                        ]) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        
        </table>
        <div class="float-right">
        </div>
    </div>
</div>
@endsection

resources/views/backend/suppliers/show.blade.php
@extends('backend.layouts.master')

@section('content')
    <div class="card">
        <div class="card-header">
            <div class="float-left">
                Supplier Details
            </div>
            <div class="float-right">
                <a href="{{ route('suppliers.index') }}" class="btn btn-primary">List</a>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped">
                <thead class="table-dark">
                <tr>
                    <th>Title</th>
                    <th>Details</th>
                </tr>
                </thead>
                <tr>
                    <td>Supplier Name</td>
                    <td>{{ $supplier->title }}</td>
                </tr>
                <tr>
                    <td>Supplier Address</td>
                    <td>{{ $supplier->address }}</td>
                </tr>
            </table>
        </div>
    </div>
@endsection

resources/views/backend/suppliers/trash.blade.php
@extends('backend.layouts.master')

@section('content')
    <div class="card">
        <div class="card-header">
            <div class="float-left">
                Deleted Categories
            </div>
            <div class="float-right">
                <a href="{{ route('categories.index') }}" class="btn btn-primary">List</a>
            </div>
        </div>
        <div class="card-body">

            @if (session()->has('message'))
                {{ session('message') }}
            @endif
            <table class="table table-bordered table-striped">
                <tr>
                    <th width="100">SL#</th>
                    <th>Title</th>
                    <th width="220" class="text-right">Action</th>
                </tr>
                @php $serial = 0; @endphp
                @foreach($categories as $category)
                    <tr>
                        <td>{{ ++$serial }}</td>
                        <td>{{ $category->title }}</td>
                        <td class="text-right">
                            <a href="{{ route('categories.show', $category->id) }}" class="btn btn-sm btn-primary">Show</a>
                            <a href="{{ route('categories.restore', $category->id) }}" class="btn btn-sm btn-warning">Restore</a>
                            {!! Form::open([
                                            'route' => ['categories.delete', $category->id],
                                            'method' => 'delete',
                                            'style' => 'display:inline',
                                        ]) !!}
                            {!! Form::button('Delete',[
                                    'type' => 'submit',
                                    'class' => "btn btn-sm btn-danger",
                                    'onclick' => 'return confirm("Are You Sure Want To Delete Permanently ?")',

                            ]) !!}
                            {!! Form::close() !!}
                            {{--</a>--}}
                        </td>
                    </tr>
                @endforeach
            </table>
            <div class="float-right">
                {{ $categories->links() }}
            </div>
        </div>
    </div>
@endsection